use_lockfile = false

[project]
name = "reportifyr"
r_version = "4.5"

repositories = [
	{ alias = "PRISM", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2026-04-30/" },
    { alias = "pyro", url = "https://prism.dev.a2-ai.cloud/rpkgs/fyrverse/v1" },
    { alias = "CRAN", url = "https://cran.r-project.org" },
]

dependencies = [
	{ name = "reportifyr", path = ".", dependencies_only = true, install_suggestions = true },
	{ name = "pyro", repository = "pyro" },
	{ name = "gdtools", repository = "CRAN" },
	"devtools",
]
