use_lockfile = false

[project]
name = "reportifyr"
r_version = "4.6"

repositories = [
	{ alias = "PRISM", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2026-07-16/" },
    { alias = "CRAN", url = "https://cran.r-project.org" },
]

dependencies = [
	{ name = "reportifyr", path = ".", install_suggestions = true },
	{ name = "tblkit", git = "https://github.com/a2-ai-scientific-software/tblkit", branch = "producer-markers", directory = "rpkg" },
	{ name = "pyro", git = "https://github.com/a2-ai/pyro", branch = "dev" },
	{ name = "gdtools", repository = "CRAN" },
	"devtools",
]
