use_lockfile = false

[project]
name = "reportifyr"
r_version = "4.4"

repositories = [
	#{ alias = "PRISM", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2025-07-28/" },
	{alias = "ppm", url = "https://packagemanager.posit.co/cran/latest"},
]

dependencies = [
	"devtools",
	{name = "reportifyr", path = ".", dependencies_only = true, install_suggestions = true },
]
