report_dir_name: "report"

outputs_dir_name: "OUTPUTS"

footnotes_font: "Arial Narrow"
footnotes_font_size: 10
use_object_path_as_source: FALSE
wrap_path_in_[]: TRUE
footnote_order:
  - Source
  - Object
  - Notes
  - Abbreviations
