sync_reportifyr_project <- function(project_dir, report_dir_name) {
  # read in init.json files
  if (!is.null(report_dir_name)) {
    path_name <- sub("/", "_", report_dir_name)
  } else {
    path_name <- "report"
  }
  init_file <- file.path(project_dir, paste0(".", path_name, "_init.json"))
  init <- jsonlite::read_json(init_file, simplifyVector = TRUE)
  # bool for later use
  update_init_file <- FALSE

  # Grab python dep info
  uv_path <- get_uv_path()
  args <- get_args(uv_path)
  pyvers <- get_py_version(getOption("venv_dir"))
  args <- c(args, pyvers)
  args_name <- c(
    "venv_dir",
    "python-docx.version",
    "pyyaml.version",
    "pillow.version",
    "uv.version",
    "python.version"
  )
  py_version_data <- stats::setNames(as.list(args), args_name)
  # check init against current py dep requests
  if (!identical(init$python_versions, py_version_data)) {
    message(
      paste0(
        "Python dependency versions have been changed, updating ",
        init_file
      )
    )
    initialize_python(continue = "Y")
    update_init_file <- TRUE
  }
  # Check config
  config <- yaml::read_yaml(
    file.path(project_dir, report_dir_name, "config.yaml"),
		handlers = list(logical = yaml::verbatim_logical)
  )

  if (!identical(config, init$config)) {
    message(
      paste0(
        "Configuration has changed, updating ",
        init_file
      )
    )
    if (config$report_dir_name != init$config$report_dir_name) {
      warning(
        paste0(
          "report_dir_name has been changed in config.yaml. \n",
          "  Please reconcile names\n",
          "\told: ",
          init$config$report_dir_name,
          "\n",
          "\tnew: ",
          config$report_dir_name
        )
      )
      config$report_dir_name <- init$config$report_dir_name
    }

    if (config$outputs_dir_name != init$config$outputs_dir_name) {
      warning(
        paste0(
          "outputs_dir_name has been changed in config.yaml. \n",
          "  Please reconcile names \n",
          "\told: ",
          init$config$outputs_dir_name,
          "\n",
          "\tnew: ",
          config$outputs_dir_name
        )
      )
      config$outputs_dir_name <- init$config$outputs_dir_name
    }
    update_init_file <- TRUE
  }

  if (update_init_file) {
    message("Updated")
    init$last_modified <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
    init$user <- Sys.info()[["user"]]
    init$python_versions <- py_version_data
    init$config <- config

    json_data <- jsonlite::toJSON(init, pretty = TRUE, auto_unbox = TRUE)
    json_with_comment <- paste(
      "// WARNING: This file is automatically generated on initialization. Do not edit by hand!",
      json_data,
      sep = "\n"
    )
    write(json_with_comment, file = init_file)
  } else {
    message("Nothing to do")
  }
}
