# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: main
  pull_request:
    branches: main

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,  r: '4.5'}
          - {os: ubuntu-latest,  r: '4.4'}
          - {os: ubuntu-latest,  r: '4.3'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: a2-ai/setup-rv@main

      - name: replace-rversion
        run: |
          perl -i -pe 's|^r_version = "4\.[0-9\.]+"$|r_version = "${{ matrix.config.r }}"|' rproject.toml
          cat rproject.toml

      - name: rv-plan
        run: rv plan

      - name: rv-sysdeps-install (Linux)
        run: |
          MISSING_DEPS=$(rv plan --json | jq -r '.installed[].sys_deps[]? | select(.status == "absent") | .name')
          if [ -n "$MISSING_DEPS" ]; then
            echo "Found missing system dependencies:"
            echo "$MISSING_DEPS"
            echo "Installing..."
            echo "$MISSING_DEPS" | xargs sudo apt install
          else
            echo "All system dependencies are present"
          fi
      - name: rv-sync
        run: rv sync

      - run: git config --global user.email "r-cmd-check@github.com"
      - run: git config --global user.name "r-cmd-check"

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
